// Extracts the design tokens + typography utilities out of the site's COMPILED
// Tailwind v4 bundle and emits app/theme.generated.css as real @theme source,
// so Tailwind's JIT generates utilities from our markup again.
//
// NOTE: reads the compiled bundle, which we keep formatted. Re-run after a
// fresh site-dump: node scripts/extract-theme.mjs
import { readFile, writeFile } from 'node:fs/promises';

const SRC = new URL(
  '../site-dump/assets/sfcompute.com/vc-ap-d5fa6a/_next/static/immutable/chunks/127pf9ia_uvmn.css',
  import.meta.url,
).pathname;
const css = await readFile(SRC, 'utf8');

// --- 1. theme tokens: the `@layer theme { :root, :host { ... } }` block ---
const themeStart = css.indexOf(':root,\n  :host {');
const themeEnd = css.indexOf('\n  }', themeStart);
const tokens = css
  .slice(css.indexOf('{', themeStart) + 1, themeEnd)
  .split('\n')
  .map((l) => l.trim())
  .filter((l) => l.startsWith('--'))
  .map((l) => '  ' + l);

// --- 2. the t-* typography utilities (plus their media variants) ---
const TYPO = [
  't-h1', 't-h3', 't-mono', 't-header', 't-input', 't-nav', 't-nav-sm',
  't-pl', 't-pm', 't-pm-medium', 't-ps', 't-pxs', 't-pxs-medium', 't-pxxl', 't-pxxs',
];
function grab(name) {
  const re = new RegExp(`^  \\.${name.replace('-', '\\-')} \\{$`, 'm');
  const m = re.exec(css);
  if (!m) return null;
  const end = css.indexOf('\n  }', m.index);
  const body = css.slice(css.indexOf('{', m.index) + 1, end).trim();
  return body.split('\n').map((l) => '  ' + l.trim()).join('\n');
}
const utilities = TYPO.map((n) => {
  const body = grab(n);
  if (!body) { console.warn('missing utility', n); return ''; }
  return `@utility ${n} {\n${body}\n}`;
}).filter(Boolean);


// --- 3. semantic tokens (--tag-*, --fg-*, --bg-*, elevation, ...) ---
// These live in ~50 separate `:root` / `[data-theme="light"]` blocks across the
// compiled bundle rather than in @theme, because they are aliases that resolve
// against the theme tokens. Tailwind reads them through arbitrary values like
// `bg-[var(--tag-green-bg)]`, so they belong in a plain :root, not @theme.
const rootBlocks = [];
{
  const re = /(?:^|\n)([^\n{}]*(?::root|\[data-theme="light"\])[^\n{}]*)\{/g;
  let m;
  while ((m = re.exec(css))) {
    if (/dark/.test(m[1])) continue;
    let depth = 0;
    let end = m.index + m[0].length - 1;
    for (let j = end; j < css.length; j++) {
      if (css[j] === '{') depth++;
      else if (css[j] === '}') { depth--; if (depth === 0) { end = j; break; } }
    }
    rootBlocks.push(css.slice(m.index + m[0].length, end));
  }
}
const semantic = new Map();
for (const body of rootBlocks) {
  for (const [, k, v] of body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) {
    if (!semantic.has(k)) semantic.set(k, v.trim());
  }
}
// Tokens already emitted in @theme would be redundant here.
const themeNames = new Set(tokens.map((l) => l.trim().split(':')[0]));
const semanticLines = [...semantic]
  .filter(([k]) => !themeNames.has(k))
  .map(([k, v]) => `  ${k}: ${v};`);

// t-h3 has a >=1000px bump; Tailwind @utility can't hold a bare media query,
// so it rides along as a plain rule below.
const out = `/* GENERATED by scripts/extract-theme.mjs — do not edit by hand.
   Tokens lifted verbatim from the source site's compiled Tailwind v4 bundle. */

@theme {
${tokens.join('\n')}
}

:root {
${semanticLines.join('\n')}
}

${utilities.join('\n\n')}

@media (min-width: 1000px) {
  .t-h3 {
    font-size: 22px;
  }
}
`;
await writeFile(new URL('../app/theme.generated.css', import.meta.url).pathname, out);
console.log(`wrote ${tokens.length} theme tokens, ${semanticLines.length} semantic tokens, ${utilities.length} utilities`);
