// Extracts the design tokens + typography utilities out of the site's COMPILED
// Tailwind v4 bundle and emits app/theme.generated.css as real @theme source,
// so Tailwind's JIT generates utilities from our markup again.
//
// NOTE: reads the compiled bundle, which we keep formatted. Re-run after a
// fresh site-dump: node scripts/extract-theme.mjs
import { readFile, writeFile } from 'node:fs/promises';

const SRC = new URL(
  '../site-dump/assets/sfcompute.com/vc-ap-d5fa6a/_next/static/immutable/chunks/127pf9ia_uvmn.css',
  import.meta.url,
).pathname;
const css = await readFile(SRC, 'utf8');

// --- 1. theme tokens: the `@layer theme { :root, :host { ... } }` block ---
const themeStart = css.indexOf(':root,\n  :host {');
const themeEnd = css.indexOf('\n  }', themeStart);
const tokens = css
  .slice(css.indexOf('{', themeStart) + 1, themeEnd)
  .split('\n')
  .map((l) => l.trim())
  .filter((l) => l.startsWith('--'))
  .map((l) => '  ' + l);

// --- 2. the t-* typography utilities (plus their media variants) ---
const TYPO = [
  't-h1', 't-h3', 't-mono', 't-header', 't-input', 't-nav', 't-nav-sm',
  't-pl', 't-pm', 't-pm-medium', 't-ps', 't-pxs', 't-pxs-medium', 't-pxxl', 't-pxxs',
];
function grab(name) {
  const re = new RegExp(`^  \\.${name.replace('-', '\\-')} \\{$`, 'm');
  const m = re.exec(css);
  if (!m) return null;
  const end = css.indexOf('\n  }', m.index);
  const body = css.slice(css.indexOf('{', m.index) + 1, end).trim();
  return body.split('\n').map((l) => '  ' + l.trim()).join('\n');
}
const utilities = TYPO.map((n) => {
  const body = grab(n);
  if (!body) { console.warn('missing utility', n); return ''; }
  return `@utility ${n} {\n${body}\n}`;
}).filter(Boolean);

// t-h3 has a >=1000px bump; Tailwind @utility can't hold a bare media query,
// so it rides along as a plain rule below.
const out = `/* GENERATED by scripts/extract-theme.mjs — do not edit by hand.
   Tokens lifted verbatim from the source site's compiled Tailwind v4 bundle. */

@theme {
${tokens.join('\n')}
}

${utilities.join('\n\n')}

@media (min-width: 1000px) {
  .t-h3 {
    font-size: 22px;
  }
}
`;
await writeFile(new URL('../app/theme.generated.css', import.meta.url).pathname, out);
console.log(`wrote ${tokens.length} tokens, ${utilities.length} utilities`);
